name: neighboring_countries
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  build: ^2.4.1
  build_runner: ^2.4.11
  html: ^0.15.4
  http: ^1.2.1
  lints: ^2.0.0
  source_gen: ^1.5.0
  test: ^1.21.0
